###
GET http://106.13.64.53:9999/api/exchanges
Accept: application/json
Authorization: Basic test testtset123+

###
GET http://106.13.64.53:9999/api/exchanges/%2F
Accept: application/json
Authorization: Basic test testtset123+

###
GET http://106.13.64.53:9999/api/exchanges/%2F/testExchange10
Accept: application/json
Authorization: Basic test testtset123+

###
PUT http://106.13.64.53:9999/api/exchanges/%2F/testExchange
Accept: application/json
Authorization: Basic test testtset123+

{
"type":"direct",
"auto_delete":false,
}

###
DELETE http://106.13.64.53:9999/api/exchanges/%2F/testExchange?if-unused=true
Accept: application/json
Authorization: Basic test testtset123+

###
GET http://106.13.64.53:9999/api/exchanges/%2F/testExchange/bindings/source
Accept: application/json
Authorization: Basic test testtset123+

