variables:
  PROJECT_NAME: "onirii"
  VERSION: "2.0.0-alpha"

stages:
  - test
  - sonar
  - publish

test:
  stage: test
  tags:
    - build
  script:
    - yarn install
    - npm run test

sonar:
  stage: sonar
  only:
    - master
    - /^feature-.*$/
    - /^hotfix-.*$/
    - /^release-.*$/
  tags:
    - build
  script:
    - |
      sonar-scanner \
      -Dsonar.projectKey=$PROJECT_NAME \
      -Dsonar.projectName=$PROJECT_NAME \
      -Dsonar.projectVersion=$VERSION \
      -Dsonar.host.url=https://sonar.heavenark.com \
      -Dsonar.login=$SONAR_KEY

publish:
  stage: publish
  only:
    - master
  tags:
    - build
  script:
    - yarn install
    - npm config set registry https://registry.npmjs.org/
    - npm run deploy
    - npm config set registry https://nexus.heavenark.com/repository/npm-public/
