variables:
  PROJECT_NAME: "Onirii"
  VERSION: "1.0.0-beta1"

stages:
  - test
  - sonar

test:
  stage: test
  retry: 2
  tags:
    - build
  script:
    - npm install
    - ./node_modules/jest/bin/jest ./test

sonar:
  stage: sonar
  tags:
    - build
  script:
    - |
      sonar-scanner \
      -Dsonar.projectKey=$PROJECT_NAME \
      -Dsonar.projectName=$PROJECT_NAME \
      -Dsonar.projectVersion=$VERSION \
      -Dsonar.host.url=https://sonar.heavenark.com \
      -Dsonar.login=38fd4defb6216085372051f675776ad81626915b
