variables:
  PROJECT_NAME: "Onirii"
  VERSION: "1.3.1"

stages:
  - test
  - sonar
  - publish

test:
  stage: test
  only:
    - master
    - /^release-.*$/
    - /^test-.*$/
  tags:
    - build
  script:
    - yarn install
    - npm run test

sonar:
  stage: sonar
  only:
    - /^feature-.*$/
    - /^style-.*$/
    - /^fix-.*$/
  tags:
    - build
  script:
    - |
      sonar-scanner \
      -Dsonar.projectKey=$PROJECT_NAME \
      -Dsonar.projectName=$PROJECT_NAME \
      -Dsonar.projectVersion=$VERSION \
      -Dsonar.host.url=https://sonar.heavenark.com \
      -Dsonar.login=38fd4defb6216085372051f675776ad81626915b

publish:
  stage: publish
  only:
    - /^release-.*$/
  tags:
    - build
  script:
    - yarn install
    - npm config set registry https://registry.npmjs.org/
    - npm run deploy
    - npm config set registry https://nexus.heavenark.com/repository/npm-private/
    - npm run deploy
    - npm config set registry https://nexus.heavenark.com/repository/npm-public/

