version: '3'

services:
  rabbit-c1:
    image: rabbitmq:3.8.16-management-alpine
    container_name: rabbit-c1
    hostname: rabbit-c1
    ports:
      - "5100:15672"
      - "5000:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=testtset123+
    volumes:
      - /data/docker/data/rabbitmq/rabbit-c1:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro


  rabbit-c2:
    image: rabbitmq:3.8.16-management-alpine
    container_name: rabbit-c2
    hostname: rabbit-c2
    restart: always
    ports:
      - "5101:15672"
      - "5001:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=testtset123+
    volumes:
      - /data/docker/data/rabbitmq/rabbit-c2:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro


  rabbit-c3:
    image: rabbitmq:3.8.16-management-alpine
    container_name: rabbit-c3
    hostname: rabbit-c3
    restart: always
    ports:
      - "5102:15672"
      - "5002:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=testtset123+
    volumes:
      - /data/docker/data/rabbitmq/rabbit-c3:/var/lib/rabbitmq
      - /etc/localtime:/etc/localtime:ro

  haproxy:
    image: haproxy:2.4.0-alpine
    container_name: haproxy
    hostname: haproxy
    restart: always
    ports:
      - "8888:8888"
      - "9999:9999"
    volumes:
      - /data/docker/data/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /etc/localtime:/etc/localtime:ro
