version: '3'

services:
  rabbit:
    image: rabbitmq:3.8.16-management-alpine
    container_name: rabbit-mq
    restart: always
    ports:
      - 10000:15672
      - 5672:5672
    volumes:
      - /home/docker/data/rabbitmq:/var/lib/rabbitmq
    environment:
      - SERVRENAME=rabbit-mq
      - RABBITMQ_HIPE_COMPILE=1
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - mq-server


networks:
  mq-server:
    external: false
