version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /nas/app-prod-server/docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /nas/app-prod-server/docker/config/nginx/server-config:/server-config
      - /nas/app-prod-server/docker/config/nginx/ssl:/ssl
      - /nas/app-prod-server/docker/data/nginx/log:/log
    environment:
      SERVER_NAME: nginx
    networks:
      - mq-server

  rabbit:
    image: rabbitmq:3.8.16-management-alpine
    container_name: rabbit-mq
    restart: always
    ports:
      - 10000:15672
    volumes:
      - /nas/app-prod-server/docker/data/rabbitmq:/var/lib/rabbitmq
    environment:
      - SERVRENAME=rabbit-mq
      - RABBITMQ_HIPE_COMPILE=1
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - mq-server


networks:
  mq-server:
    external: false